name: demo github actions

# to automatically trigger workflow
on:
  push: 
      branches: ["master"]
  pull_request:
      branches: ["master"]

  #for manual trigger
  workflow_dispatch:

# main work to be performed
jobs:
  #job1
  build0:
    runs-on: ubuntu-latest
    steps:
      - run: echo build0

  build1:
     runs-on: ubuntu-latest
     steps:
      - run: echo build1
      
  build2:
     needs: [build0, build1]
     runs-on: ubuntu-latest
     steps:
      - run: echo build2
      
  

      
